# Fluid configurations
favicon: /images/avatars/avatar.jpg

custom_css: /assets/custom.css

custom_html: '<script defer src="https://vercount.one/js"></script><script src="https://kit.fontawesome.com/e3536555f9.js" crossorigin="anonymous"></script>'

color:
  navbar_bg_color: '#4684cc'

navbar:
  banner_img: /images/banners/index.jpg
  banner_img_height: 70
  blog_title: 瑞凤小站
  menu:
    - { key: "home", link: "/", icon: "fa-solid fa-house" }
    - { key: "archive", link: "/archives/", icon: "fa-solid fa-folder" }
    - { key: "category", link: "/categories/", icon: "fa-solid fa-list" }
    - { key: "tag", link: "/tags/", icon: "fa-solid fa-tags" }
    - { key: "about", link: "/about/", icon: "fa-solid fa-user" }

index:
  banner_img: /images/banners/index.jpg
  banner_img_height: 100
  slogan:
    enable: true
    text: 瑞凤小站

post:
  banner_img: /images/banners/index.jpg
  banner_img_height: 30
  mermaid:
    enable: true
    specific: false

about:
  avatar: /images/avatars/avatar.jpg
  banner_img: /images/banners/index.jpg
  banner_img_height: 50
  name: "Zuiho"
  intro: "Self site of Zuiho"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/sxlllslgh', tip: 'GitHub' }
    - { class: 'iconfont icon-mail', link: 'mailto:sxlllslgh@gmail.com', tip: 'Mail' }

footer:
  content:
    '<form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
      <input type="hidden" name="cmd" value="_s-xclick" />
      <input type="hidden" name="hosted_button_id" value="T6FEKEAUUP86C" />
      <input type="hidden" name="on0" value="Donate Amount"/>
      <div style="display: flex; justify-content: center; align-items: center">
        <span>If this page help you, feel free to donate a cup of coffee to me.</span>
        <select name="os0" style="margin-left: 1rem; margin-right: 1rem">
          <option value="Five Dollars">
            Five Dollars $5.00 USD
          </option>
          <option value="Ten Dollars">
            Ten Dollars $10.00 USD
          </option>
          <option value="Fifteen Dollars">
            Fifteen Dollars $15.00 USD
          </option>
          <option value="Twenty Dollars">
            Twenty Dollars $20.00 USD
          </option>
        </select>
        <input type="hidden" name="currency_code" value="USD" />
        <input type="image" src="/images/banners/donate.svg" border="0" name="submit" title="有了PayPal，您可以更安全便捷地在线付款！" alt="Donate Now" width=100 />
      </div>
    </form>
    <a href="https://hexo.io" target="_blank" rel="nofollow noopener"><span>Hexo</span></a> <i class="iconfont icon-love"></i> <a href="https://github.com/fluid-dev/hexo-theme-fluid" target="_blank" rel="nofollow noopener"><span>Fluid</span></a><div class="statistics">
    <span id="busuanzi_container_site_pv" style="display: inline;">总访问量 <span id="busuanzi_value_site_pv">6713474</span> 次 </span><span id="busuanzi_container_site_uv" style="display: inline;">总访客数 <span id="busuanzi_value_site_uv">4074171</span> 人</span></div>'
