# Fluid configurations
navbar:
  banner_img: /images/banners/index.jpg
  blog_title: 瑞凤小站

index:
  banner_img: /images/banners/index.jpg
  slogan:
    enable: true
    text: 瑞凤小站

post:
  banner_img: /images/banners/index.jpg

about:
  avatar: /images/avatars/avatar.jpg
  name: "Zuiho"
  intro: "Self site of Zuiho"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/sxlllslgh', tip: 'GitHub' }