# Fluid configurations
favicon: /images/avatars/avatar.jpg

custom_html: '<script defer src="https://vercount.one/js"></script>'

color:
  navbar_bg_color: '#4684cc'

navbar:
  banner_img: /images/banners/index.jpg
  banner_img_height: 70
  blog_title: 瑞凤小站

index:
  banner_img: /images/banners/index.jpg
  banner_img_height: 100
  slogan:
    enable: true
    text: 瑞凤小站

post:
  banner_img: /images/banners/index.jpg
  banner_img_height: 30
  mermaid:
    enable: true
    specific: false

about:
  avatar: /images/avatars/avatar.jpg
  banner_img: /images/banners/index.jpg
  banner_img_height: 50
  name: "Zuiho"
  intro: "Self site of Zuiho"
  icons:
    - { class: 'iconfont icon-github-fill', link: 'https://github.com/sxlllslgh', tip: 'GitHub' }
    - { class: 'iconfont icon-mail', link: 'mailto:sxlllslgh@gmail.com', tip: 'Mail' }

footer:
  content: '<div class="statistics"><span id="busuanzi_container_site_pv" style="display: inline;">总访问量 <span id="busuanzi_value_site_pv">6713474</span> 次 </span><span id="busuanzi_container_site_uv" style="display: inline;">总访客数 <span id="busuanzi_value_site_uv">4074171</span> 人</span></div>'
